// © 2026 LearnHubPlay BV. All rights reserved.
// Licensed under BUSL 1.1 — see LICENSE for details.
// LokaLLM™ — lokaflow.io
//
// packages/lokallm/src/exporter.ts
// GGUFExporter — merge LoRA adapters and export to GGUF format via gguf.py.

import { EventEmitter } from "events";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { PythonRunner, type RunnerEvent } from "./runner.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GGUF_SCRIPT = join(__dirname, "export", "gguf.py");

// ── Types ──────────────────────────────────────────────────────────────────

export interface ExportConfig {
  /** Path to trained LoRA adapter directory */
  adapter: string;
  /** Path for the output .gguf file */
  output: string;
  /** Base model HuggingFace ID */
  baseModel?: string;
  /** Python binary override */
  pythonBin?: string;
}

export type ExporterEvent =
  | { type: "start"; config: ExportConfig }
  | { type: "log"; level: "info" | "warn"; message: string }
  | { type: "complete"; ggufPath: string; durationMs: number }
  | { type: "error"; error: Error };

// ── GGUFExporter ───────────────────────────────────────────────────────────

/**
 * Wraps `src/export/gguf.py` — merges LoRA weights into base model and
 * exports to GGUF format ready for Ollama import.
 *
 * Emits `ExporterEvent` objects on the `"data"` event for progress reporting.
 */
export class GGUFExporter extends EventEmitter {
  private runner?: PythonRunner;
  private startedAt?: number;

  async export(config: ExportConfig): Promise<string> {
    this.startedAt = Date.now();

    const args = ["--adapter", config.adapter, "--output", config.output];
    if (config.baseModel) args.push("--base_model", config.baseModel);

    this.runner = new PythonRunner(GGUF_SCRIPT, {
      args,
      ...(config.pythonBin !== undefined && { pythonBin: config.pythonBin }),
    });

    this.emit("data", { type: "start", config } satisfies ExporterEvent);

    this.runner.on("data", (ev: RunnerEvent) => {
      if (ev.type === "stdout" || ev.type === "stderr") {
        const level = ev.type === "stderr" ? "warn" : "info";
        this.emit("data", { type: "log", level, message: ev.line } satisfies ExporterEvent);
      }
    });

    return new Promise<string>((resolve, reject) => {
      this.runner!.run()
        .then(() => {
          const durationMs = Date.now() - (this.startedAt ?? Date.now());
          this.emit("data", {
            type: "complete",
            ggufPath: config.output,
            durationMs,
          } satisfies ExporterEvent);
          resolve(config.output);
        })
        .catch((err: Error) => {
          this.emit("data", { type: "error", error: err } satisfies ExporterEvent);
          reject(err);
        });
    });
  }

  /**
   * Generate an Ollama Modelfile for the exported GGUF.
   * Returns the Modelfile content as a string.
   */
  generateOllamaModelfile(ggufPath: string, template = "phi3"): string {
    const templates: Record<string, string> = {
      phi3: `<|user|>\n{{ .Prompt }}<|end|>\n<|assistant|>`,
      llama3: `<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n{{ .Prompt }}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n`,
      mistral: `[INST] {{ .Prompt }} [/INST]`,
    };

    const tmpl = templates[template] ?? templates["phi3"];

    return [
      `# Ollama Modelfile — generated by LokaLLM™ GGUFExporter`,
      `FROM ${ggufPath}`,
      "",
      `TEMPLATE """${tmpl}"""`,
      "",
      `PARAMETER stop "<|end|>"`,
      `PARAMETER stop "<|user|>"`,
      `PARAMETER temperature 0.7`,
      `PARAMETER top_p 0.95`,
    ].join("\n");
  }

  stop(): void {
    this.runner?.kill();
  }
}
