name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please check the [VISION.md](../VISION.md)
        first to see if it aligns with where LokaFlow is headed.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case and the pain point clearly.
      placeholder: "When I try to do X, I can't because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any other approaches or workarounds you've tried?

  - type: dropdown
    id: area
    attributes:
      label: Which area does this affect?
      multiple: true
      options:
        - Router / task classification
        - Local model integration (Ollama)
        - Cloud model adapter (Claude / OpenAI)
        - PII scanner / privacy
        - Task graph / orchestration
        - CLI interface
        - VS Code plugin
        - API / SDK
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked VISION.md and this fits the project direction
          required: true
        - label: I searched existing issues and this is not a duplicate
          required: true
